name = "zen-ad-server"
main = "src/index.js"
compatibility_date = "2024-09-01"

# Optional: Attach custom domain or route if your zone is on Cloudflare
# routes = [
#   { pattern = "ads.mvzen.com/*", zone_name = "mvzen.com" }
# ]
